config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams, param: :slug do
    resources :teams_users, only: %i[show create edit update destroy]

    resources :events, only: %i[show new create edit update destroy], param: :slug do
      resources :event_occurrences, only: %i[destroy]
      resources :schedule_recurrences, only: %i[create]
      resources :schedule_occurrences, only: %i[create]
      resources :alarms, only: %i[index new create edit update destroy]
    end
  end

  resources :main, only: %i[index]
  resources :users, only: %i[index update], param: :username

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
end

app/models/alarm.rb
# frozen_string_literal: true

# Alarms are responsible for keeping track when to notify of event occurances
class Alarm < ApplicationRecord
  self.implicit_order_column = :created_at

  belongs_to :alarmable, polymorphic: true
  belongs_to :event

  def interval
    calculate_trigger[0]
  end

  def interval=(value)
    @interval = value
    calculate_into_trigger
  end

  def period
    calculate_trigger[1]
  end

  def self.periods
    %w[hour minute second]
  end

  def period=(value)
    return unless Alarm.periods.include?(value)

    @period = value
    calculate_into_trigger
  end

  def alarm_time(_time)
    date - trigger.seconds
  end

  def notification_data(event_occurrence)
    { title: event.name,
      description: description.presence || event.description,
      time: event_occurrence.starts_at }
  end

  private

  def calculate_into_trigger
    return nil unless @period && @interval

    self.trigger = @interval.to_i.send(@period).seconds
  end

  def calculate_trigger
    return [nil, nil] unless trigger
    return [trigger / 3600, 'hour'] if (trigger % 3600).zero?
    return [trigger / 60, 'minute'] if (trigger % 60).zero?

    [trigger, 'second']
  end
end

app/controllers/alarms_controller.rb
# frozen_string_literal: true

# The controller used for setting up and managing alarms for individual
# Events
class AlarmsController < ApplicationController
  before_action :set_team
  before_action :set_event
  before_action :set_alarm, only: %i[edit update destroy]

  def index
    @alarms = policy_scope(Alarm).where(event: @event)
  end

  def new
    @alarm = authorize @event.alarms.new, policy_class: AlarmPolicy
  end

  def edit
    authorize @alarm, policy_class: AlarmPolicy
  end

  def create
    @alarm = authorize @event.alarms.new(alarm_params), policy_class: AlarmPolicy

    if @alarm.save
      redirect_to team_event_alarms_url(@team, @event, @alarm), notice: I18n.t('alarms.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @alarm, policy_class: AlarmPolicy

    if @alarm.update(alarm_params)
      redirect_to team_event_alarms_url(@team, @event, @alarm), notice: I18n.t('alarms.updated')
    else
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @alarm, policy_class: AlarmPolicy

    @alarm.destroy
    redirect_to team_event_alarms_url(@team, @event), notice: I18n.t('alarms.removed')
  end

  private

  def alarm_params
    type = %i[alarm alarm_email alarm_notification].map { |t| params.key?(t) ? t : nil }.compact.first
    params.require(type).permit(:type, :email, :interval, :period, :description, :alarmable_type, :alarmable_id)
  end
end

app/views/alarms/edit.html.haml
%h1= t('alarms.edit_title')
= form_with(model: @alarm, url: team_event_alarm_path(@team, @event, @alarm),
            html: { 'data-controller': 'alarm-form' }) do |f|
  - if @alarm.errors.any?
    - @alarm.errors.full_messages.each do |msg|
      .alert.alert-danger
        = msg
  = f.hidden_field :alarmable_type, value: params[:team] ? @team.class.name : current_user.class.name
  = f.hidden_field :alarmable_id, value: params[:team] ? @team.id : current_user.id
  .input-group.mb-3
    .form-floating
      = f.select :type, { t('alarms.email') => 'AlarmEmail', t('alarms.notification') => 'AlarmNotification' },
                 {}, class: 'form-select', placeholder: t('alarms.type'),
                     data: { action: 'alarm-form#toggleEmail', 'alarm-form-target': 'type' }
      = f.label :type, t('alarms.type')
    .form-floating{ data: { 'alarm-form-target': 'email' } }
      = f.email_field :email, class: 'form-control', placeholder: t('alarms.email_address')
      = f.label :email, t('alarms.email_address')
  .input-group.mb-3.align-items-center.w-auto
    = t('alarms.trigger_html', number: f.number_field(:interval, class: 'form-control mx-1'),
                               period: f.select(:period, Alarm.periods.map { |p| t("period.#{p}") },
                                                {}, class: 'form-select mx-1'))
  .form-floating.mb-3
    = f.text_area :description, class: 'form-control h-min', placeholder: t('alarms.description')
    = f.label :description, t('alarms.description')
  = f.submit t('alarms.save'), class: 'btn btn-primary'

app/views/alarms/index.html.haml
%h1.d-flex.justify-content-between
  %span
    = t('alarms.index_title_html', event: link_to(@event.name, [@team, @event]))
  .buttons
    - if policy(@event.alarms.new).team_create?
      = link_to new_team_event_alarm_path(@team, @event, team: true), class: 'btn btn-success me-1' do
        = t('alarms.create_team')
    - if policy(@event.alarms.new).create?
      = link_to new_team_event_alarm_path(@team, @event), class: 'btn btn-success' do
        = t('alarms.create')
- @alarms.each do |alarm|
  .card.card-body.mb-3
    .d-flex.justify-content-between
      = link_to edit_team_event_alarm_path(@team, @event, alarm) do
        %h3.mb-0
          %span
            - if alarm.action == 'EMAIL'
              = t('alarms.email_for', email: alarm.email.presence || alarm.alarmable.email)
            - else
              - identifier = alarm.alarmable.instance_of?(User) ? alarm.alarmable.username : alarm.alarmable.name
              = t('alarms.notification_for', notifiable: identifier)
      .buttons
        - if policy(alarm).destroy?
          = button_to t('alarms.remove'), team_event_alarm_path(@team, @event, alarm), method: :delete,
                                                                                       form: { class: 'd-inline' },
                                                                                       class: 'btn btn-danger'
    %p
      = t('alarms.triggered', amount: t("interval.#{alarm.period}", count: alarm.interval))
    - if alarm.description.present?
      %h5= t('alarms.description')
      %pre= alarm.description

app/views/alarms/new.html.haml
%h1= t('alarms.create_title')
= form_with(model: Alarm.new, url: team_event_alarms_path(@team, @event),
            html: { 'data-controller': 'alarm-form' }) do |f|
  - if @alarm.errors.any?
    - @alarm.errors.full_messages.each do |msg|
      .alert.alert-danger
        = msg
  = f.hidden_field :alarmable_type, value: params[:team] ? @team.class.name : current_user.class.name
  = f.hidden_field :alarmable_id, value: params[:team] ? @team.id : current_user.id
  .input-group.mb-3
    .form-floating
      = f.select :type, { t('alarms.email') => 'AlarmEmail', t('alarms.notification') => 'AlarmNotification' },
                 {}, class: 'form-select', placeholder: t('alarms.type'), data: { action: 'alarm-form#toggleEmail',
                                                                                  'alarm-form-target': 'type' }
      = f.label :type, t('alarms.type')
    .form-floating{ data: { 'alarm-form-target': 'email' } }
      = f.email_field :email, class: 'form-control', placeholder: t('alarms.email_address')
      = f.label :email, t('alarms.email_address')
  .input-group.mb-3.align-items-center.w-auto
    = t('alarms.trigger_html', number: f.number_field(:interval, class: 'form-control mx-1'),
                               period: f.select(:period, Alarm.periods.map { |p| t("period.#{p}") },
                                                {}, class: 'form-select mx-1'))
  .form-floating.mb-3
    = f.text_area :description, class: 'form-control h-min', placeholder: t('alarms.description')
    = f.label :description, t('alarms.description')
  = f.submit t('alarms.create'), class: 'btn btn-primary'