config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams, param: :slug do
    resources :teams_users, only: %i[show create edit update destroy]

    resources :events, only: %i[show new create edit update destroy], param: :slug do
      resources :event_occurrences, only: %i[destroy]
      resources :schedule_recurrences, only: %i[create]
      resources :schedule_occurrences, only: %i[create]
      resources :alarms, only: %i[index new create edit update destroy]
    end
  end

  resources :main, only: %i[index]
  resources :users, only: %i[index update], param: :username

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
end

app/views/shared/_devise_links.html.haml
- if Devise.mappings[:user].recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t(:forgot_password), new_password_path(:user)
  %br/
- if Devise.mappings[:user].confirmable? && controller_name != 'confirmations'
  = link_to t(:no_confirmation_instructions), new_confirmation_path(:user)
  %br/
- if Devise.mappings[:user].lockable? && User.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t(:no_unlock_instructions), new_unlock_path(:user)
  %br/

app/views/shared/_subscribe_links.html.haml
- url_with_webcal = URI(url)
- url_with_webcal.scheme = 'webcal'
%span.dropdown
  = link_to(t(:subscribe), '#', class: "#{button_class} dropdown-toggle", data: { 'bs-toggle': 'dropdown' })
  %ul.dropdown-menu
    %li.dropdown-item
      = link_to(t(:webcal), url_with_webcal.to_s, class: 'dropdown-item')
    %li.dropdown-item
      = link_to(t(:google_calendar), "https://www.google.com/calendar/render?cid=#{url_with_webcal}",
                class: 'dropdown-item')
    %li.dropdown-item{ data: { controller: 'clipboard' } }
      %input.visually-hidden{ value: url, data: { 'clipboard-target': 'source' } }
      = link_to(t(:copy_ical), url, class: 'dropdown-item', data: { action: 'clipboard#copy' })