config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams, param: :slug do
    resources :teams_users, only: %i[show create edit update destroy]

    resources :events, only: %i[show new create edit update destroy], param: :slug do
      resources :event_occurrences, only: %i[destroy]
      resources :schedule_recurrences, only: %i[create]
      resources :schedule_occurrences, only: %i[create]
      resources :alarms, only: %i[index new create edit update destroy]
    end
  end

  resources :main, only: %i[index]
  resources :users, only: %i[index update], param: :username

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
end

app/models/event.rb
# frozen_string_literal: true

# This represents the event object
class Event < ApplicationRecord
  self.implicit_order_column = :starts_at

  belongs_to :team
  has_many :schedule_occurrences, dependent: :destroy
  has_many :schedule_recurrences, dependent: :destroy
  has_many :occurrences, class_name: 'EventOccurrence', dependent: :destroy
  has_many :schedule_exceptions, dependent: :destroy
  has_many :alarms, dependent: :destroy
  accepts_nested_attributes_for :schedule_recurrences,
                                allow_destroy: true
  accepts_nested_attributes_for :schedule_exceptions,
                                allow_destroy: true
  accepts_nested_attributes_for :schedule_occurrences,
                                allow_destroy: true

  validates :slug,
            format: { with: /\A[a-z0-9_-]+\z/, message: I18n.t('format_validation.alphanumeric_with_dashes') }
  validates :slug, uniqueness: { scope: :team_id }

  after_save :populate_occurrences

  IEVENT_DETAILS = {
    summary: ->(event) { event.name },
    uid: ->(event) { event.id.to_s },
    description: ->(event) { event.description },
    x_alt_desc: ->(event) { Icalendar::Values::Text.new(event.html_description, { 'FMTTYPE' => 'text/html' }) },
    dtstart: ->(event) { event.ical_time(event.starts_at) },
    dtend: ->(event) { event.ical_time(event.ends_at) },
    created: ->(event) { event.ical_time(event.created_at) },
    last_modified: ->(event) { event.ical_time(event.updated_at) },
    color: ->(event) { Team::COLOR[event.team.color.to_sym] },
    url: ->(event) { Rails.application.routes.url_helpers.team_event_url(event.team, event) },
    conference: ->(event) { event.meeting_url }
  }.freeze

  ICALENDAR_DETAILS = {
    color: ->(event) { Team::COLOR[event.team.color.to_sym] },
    url: ->(event) { Rails.application.routes.url_helpers.team_event_url(event.team, event) },
    source: ->(event) { Rails.application.routes.url_helpers.team_event_url(event.team, event, format: :ics) }
  }.freeze

  def to_param
    slug
  end

  def starts_at
    super&.in_time_zone(timezone)
  end

  def ends_at
    super&.in_time_zone(timezone)
  end

  def schedule
    @schedule ||= IceCube::Schedule.new(starts_at, end_time: ends_at) do |s|
      schedule_recurrences.each { |r| s.add_recurrence_rule(r.rule) }
      schedule_exceptions.each { |x| s.add_exception_time(x.time) }
      schedule_occurrences.each { |o| s.add_recurrence_time(o.time) }
    end
  end

  def ievent
    event = Icalendar::Event.new
    IEVENT_DETAILS.each do |prop, value|
      event.send("#{prop}=", value.call(self))
    end
    event_time_properties(event)
    event
  end

  def icalendar
    Icalendar::Calendar.new.tap do |ical|
      ICALENDAR_DETAILS.each do |prop, value|
        ical.send("#{prop}=", value.call(self))
      end
      ical.add_timezone(ical_timezone)
      ical.add_event(ievent)
    end
  end

  def populate_occurrences
    destroy_old_occurrences

    schedule.occurrences(63.days.from_now)&.each do |o|
      next if occurrences.exists?(starts_at: o.start_time, ends_at: o.end_time)

      occurrences << EventOccurrence.new(starts_at: o.start_time, ends_at: o.end_time)
    end
  end

  def html_description
    Kramdown::Document.new(description, input: 'GFM').to_html
  end

  def ical_time(time)
    Icalendar::Values::DateTime.new time, tzid: ActiveSupport::TimeZone::MAPPING[timezone]
  end

  private

  def destroy_old_occurrences
    occurrences&.each do |o|
      all_occurences = schedule.occurrences_between(o.starts_at, o.ends_at)
      next if all_occurences.any? { |a| a.start_time == o.starts_at && a.end_time == o.ends_at }

      o.destroy
    end
  end

  def event_time_properties(event)
    schedule_recurrences.each { |r| event.append_rrule(r.rule.to_ical) }
    schedule_exceptions.each { |x| event.append_exdate(ical_time(x.time)) }
    schedule_occurrences.each { |o| event.append_rdate(ical_time(o.time)) }
  end

  def ical_timezone
    tzinfo = ActiveSupport::TimeZone.find_tzinfo(timezone)
    tzinfo.ical_timezone(Time.zone.now)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Controller related to event actions
class EventsController < ApplicationController
  before_action :set_team
  before_action :set_event, only: %i[show edit update destroy]

  def show
    authorize @event
    @dated_occurrences = @event.occurrences.where('starts_at > ?',
                                                  Date.yesterday).order('starts_at ASC').group_by do |o|
      o.starts_at.strftime('%B %Y')
    end

    respond_to do |format|
      format.html
      format.ics { render plain: @event.icalendar.to_ical, content_type: 'text/calendar' }
    end
  end

  def new
    @event = authorize @team.events.new
  end

  def edit
    authorize @event
  end

  def create
    @event = @team.events.new(event_parameters)

    if @event.save
      redirect_to team_event_url(@team, @event), notice: I18n.t('events.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @event

    if @event.update(event_parameters)
      redirect_to team_event_url(@team, @event), notice: I18n.t('events.updated')
    else
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to team_url(@team), notice: I18n.t('events.removed')
  end

  private

  def event_parameters
    event_params = params.require(:event).permit(
      :name, :slug, :description, :meeting_url, :starts_at, :ends_at, :timezone,
      schedule_recurrences_attributes: [
        [:id, :interval, :frequency, :_destroy, :month_type, :ends_at, { week_days: [] }]
      ],
      schedule_exceptions_attributes: [%i[id time _destroy]],
      schedule_occurrences_attributes: [%i[id time _destroy]]
    )

    apply_timezone_conversion(event_params)

    event_params
  end

  def apply_timezone_conversion(event_params)
    return unless (timezone = ActiveSupport::TimeZone[event_params[:timezone] || @event&.timezone])

    convert_time_attributes(event_params, timezone, %i[starts_at ends_at])
    convert_nested_attributes(event_params, timezone, :schedule_recurrences_attributes, :ends_at)
    convert_nested_attributes(event_params, timezone, :schedule_exceptions_attributes, :time)
    convert_nested_attributes(event_params, timezone, :schedule_occurrences_attributes, :time)
  end

  def convert_time_attributes(params, timezone, attributes)
    attributes.each { |attribute| params[attribute] = convert_time_with_zone(params[attribute], timezone) }
  end

  def convert_nested_attributes(params, timezone, nested_attribute, nested_attribute_key)
    elements = params[nested_attribute]
    return unless elements

    elements.each_value do |element|
      convert_time_attributes(element, timezone, [nested_attribute_key]) if element[nested_attribute_key]
    end
  end

  def convert_time_with_zone(time, timezone)
    timezone.parse(time) if time
  end
end

app/views/events/edit.html.haml
%h1= t('events.edit_title')
= form_with(model: @event, url: team_event_path(@team, @event),
            html: { data: { controller: 'event-form',
                            'event-form-recurrence-url-value': team_event_schedule_recurrences_path(@team, @event),
                            'event-form-occurrence-url-value': team_event_schedule_occurrences_path(@team, @event),
                            'event-form-type-value': 'edit' } }) do |f|
  - if @event.errors.any?
    - @event.errors.full_messages.each do |msg|
      .alert.alert-danger
        = msg
  .form-floating.mb-3
    = f.text_field :name, required: true, class: 'form-control', placeholder: t('events.name')
    = f.label :name, t('events.name')
  .form-floating.mb-3
    = f.text_field :slug, required: true, class: 'form-control', placeholder: t('events.slug'),
                          pattern: '^[a-z0-9_-]+$'
    = f.label :slug, t('events.slug')
  .form-floating.mb-3
    = f.text_area :description, class: 'form-control h-min mb-1', placeholder: t('events.description')
    = f.label :description, t('events.description')
    = link_to('https://www.markdownguide.org/cheat-sheet/', class: 'link-body-emphasis ms-1') do
      %i.fab.fa-markdown
      = t('events.markdown_formatting')
  .form-floating.mb-3
    = f.text_field :meeting_url, class: 'form-control', placeholder: t('events.meeting_url')
    = f.label :meeting_url, t('events.meeting_url')
  .input-group.mb-3
    .form-floating
      = f.datetime_local_field :starts_at, required: true, class: 'form-control',
                                           data: { action: 'event-form#date',
                                                   'event-form-target': 'startsAt' }
      = f.label :starts_at, t('events.starts_at')
    .form-floating
      = f.datetime_local_field :ends_at, required: true, class: 'form-control'
      = f.label :ends_at, t('events.ends_at')
    .form-floating
      = f.time_zone_select :timezone, nil, { include_blank: false }, class: 'form-select'
      = f.label :timezone, t('events.timezone')
  .mb-3
    %h4= t('schedule_recurrences.rules')
    #recurrences
      - @event.schedule_recurrences.each_with_index do |recurrence, index|
        = render partial: 'schedule_recurrences/form', locals: { index:, recurrence: }
    %button.btn.btn-success.mb-3{ type: 'button',
                                  data: { action: 'event-form#appendRecurrenceForm' } }
      = t('schedule_recurrences.add_rule')
  .mb-3
    %h4= t('schedule_occurrences.dates')
    #occurrences
      - @event.schedule_occurrences.each_with_index do |occurrence, index|
        = render partial: 'schedule_occurrences/form', locals: { index:, occurrence: }
    %button.btn.btn-success.mb-3{ type: 'button',
                                  data: { action: 'event-form#appendOccurrenceForm' } }
      = t('schedule_occurrences.add_date')
    - if @event.schedule_exceptions.present?
      %h4= t('schedule_exceptions.exceptions')
      #exceptions
        = f.fields_for :schedule_exceptions do |fe|
          .row{ data: { controller: 'exception-form' } }
            .col
              .form-floating
                = fe.datetime_local_field :time, class: 'form-control'
                = fe.label :time, t('schedule_exceptions.time')
            .col-auto
              .form-destroy
                = fe.check_box :_destroy, class: 'form-check-input'
                = fe.label :_destroy, t('schedule_exceptions.remove'), class: 'form-check-disabled'
                = fe.label :_destroy, t('schedule_exceptions.restore'), class: 'form-check-enabled'
            %hr.mt-3
  = f.submit t('events.save'), class: 'btn btn-primary'

app/views/events/new.html.haml
%h1= t('events.create_title')
= form_with(model: @event, url: team_events_path(@team), html: { data: { controller: 'event-form slug-form',
                                                                         'event-form-type-value': 'new' } }) do |f|
  - if @event.errors.any?
    - @event.errors.full_messages.each do |msg|
      .alert.alert-danger
        = msg
  .form-floating.mb-3
    = f.text_field :name, required: true, class: 'form-control', placeholder: t('events.name'),
                          data: { action: 'slug-form#prefillSlug' }
    = f.label :name, t('events.name')
  .form-floating.mb-3
    = f.text_field :slug, required: true, class: 'form-control', placeholder: t('events.slug'),
                          pattern: '^[a-z0-9_-]+$',
                          data: { 'slug-form-target': 'slug' }
    = f.label :slug, t('events.slug')
  .form-floating.mb-3
    = f.text_area :description, size: '70x5', class: 'form-control h-min mb-1', placeholder: t('events.description')
    = f.label :description, t('events.description')
    = link_to('https://www.markdownguide.org/cheat-sheet/', class: 'link-body-emphasis ms-1') do
      %i.fab.fa-markdown
      = t('events.markdown_formatting')
  .form-floating.mb-3
    = f.text_field :meeting_url, class: 'form-control', placeholder: t('events.meeting_url')
    = f.label :meeting_url, t('events.meeting_url')
  .input-group.mb-3
    .form-floating
      = f.datetime_local_field :starts_at, required: true, class: 'form-control',
                                           data: { action: 'event-form#date',
                                                   'event-form-target': 'startsAt' }
      = f.label :starts_at, t('events.starts_at')
    .form-floating
      = f.datetime_local_field :ends_at, required: true, class: 'form-control'
      = f.label :ends_at, t('events.ends_at')
    .form-floating
      = f.time_zone_select :timezone, nil, { include_blank: false }, class: 'form-select',
                                                                     data: { 'event-form-target': 'timezone' }
      = f.label :timezone, t('events.timezone')
  .mb-3
    = f.fields_for :schedule_recurrences, ScheduleRecurrence.new do |fr|
      %div{ data: { controller: 'recurrence-form' } }
        .form-check
          = fr.radio_button :_destroy, 'true', checked: true, class: 'form-check-input',
                                               data: { action: 'recurrence-form#recurrence',
                                                       'recurrence-form-target': 'repeat' }
          = fr.label :_destroy_true, t('schedule_recurrences.once'), class: 'form-check-label'
        .row.g-1.mb-3.align-items-center
          .col-auto
            .form-check
              = fr.radio_button :_destroy, 'false', checked: false, class: 'form-check-input mt-2',
                                                    data: { action: 'recurrence-form#recurrence' }
              - periods = ScheduleRecurrence.frequencies.keys.map { |p| t("period.#{p}") }
              = fr.label :_destroy_false, t('schedule_recurrences.repeat_every_html',
                                            number: fr.number_field(:interval,
                                                                    value: 1, class: 'form-control mx-1',
                                                                    data: { 'recurrence-form-target': 'interval' }),
                                            period: fr.select(:frequency,
                                                              periods, {},
                                                              class: 'form-select mx-1',
                                                              data: { action: 'recurrence-form#recurrence',
                                                                      'recurrence-form-target': 'frequency' })),
                         class: 'form-check-label input-group mb-3 align-items-center w-auto'
        .input-group.mb-3.d-none{ data: { 'event-form-target': 'week', 'recurrence-form-target': 'week' } }
          = fr.collection_check_boxes :week_days,
                                      Date::DAYNAMES.map { |d| t("dow.#{d.downcase}") }.each_with_index.to_a,
                                      :second, :first, include_hidden: false do |c|
            .form-check.me-2
              = c.check_box class: 'form-check-input'
              = c.label class: 'form-check-label'
        .form-floating.mb-3.d-none{ data: { 'event-form-target': 'month', 'recurrence-form-target': 'month' } }
          = fr.select :month_type, ScheduleRecurrence.month_types.keys.index_by(&:humanize), {}, class: 'form-control'
          = fr.label :month_type, 'Repeat on'
        .form-floating.d-none{ data: { 'recurrence-form-target': 'recurrenceEndsAt' } }
          = fr.datetime_local_field :ends_at, class: 'form-control'
          = fr.label :ends_at, t('schedule_recurrences.no_repeat_after')
  = f.submit t('events.create'), class: 'btn btn-primary'

app/views/events/show.html.haml
.row
  .col-md-8.mb-5
    %h1.d-flex.justify-content-between.text-break.flex-wrap
      = @event.name
      %span.buttons.ms-2.text-end
        = render partial: 'shared/subscribe_links', locals: { url: team_event_url(@team, @event, format: :ics),
                                                              button_class: 'btn btn-secondary' }
        - if user_signed_in?
          = link_to(t('events.alarms'), team_event_alarms_path(@team, @event),
                    class: 'btn btn-secondary')
        - if policy(@event).update?
          = link_to(t('events.edit'), edit_team_event_path(@team, @event),
                    class: 'btn btn-secondary')
        - if policy(@event).destroy?
          = button_to t('events.remove'), team_event_path(@team, @event), method: :delete,
                                                                          form: { class: 'd-inline' },
                                                                          class: 'btn btn-danger'
    - if @event.description.present?
      .row.g-2.mb-2
        .col-auto
          %i.fas.fa-fw.fa-align-left
        .col
          = markdownify(@event.description)
    - if @event.meeting_url.present?
      .row.g-2.mb-2
        .col-auto
          %i.fas.fa-fw.fa-video
        .col
          = link_to @event.meeting_url, @event.meeting_url
    .row.g-2.mb-2
      .col-auto
        %i.fas.fa-fw.fa-user-group
      .col
        = t('events.run_by_html', team: link_to(@event.team.name, team_path(@event.team)))
    .row.g-2.mb-2
      .col-auto
        %i.fas.fa-fw.fa-clock
      .col
        %div= local_time(@event.starts_at, '%B %d, %Y %H:%M %Z')
        %div= local_time(@event.ends_at, '%B %d, %Y %H:%M %Z')
    - if @event.schedule_recurrences.present?
      .row.g-2.mb-2
        .col-auto
          %i.fas.fa-fw.fa-rotate-right
        .col
          - @event.schedule_recurrences.each do |recurrence|
            %div= recurrence.rule.to_s
  .col-md-4
    - @dated_occurrences.each do |date, occurrences|
      .card.card-body.mb-3
        %h3= date
        %ul
          - occurrences.each do |occurrence|
            %li
              = range_display(occurrence.starts_at, occurrence.ends_at)
              - if policy(@event).update?
                = button_to t('event_occurrences.remove'), team_event_event_occurrence_path(@team, @event, occurrence),
                            method: :delete, form: { class: 'd-inline' }, class: 'btn btn-sm link-danger'