config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams, param: :slug do
    resources :teams_users, only: %i[show create edit update destroy]

    resources :events, only: %i[show new create edit update destroy], param: :slug do
      resources :event_occurrences, only: %i[destroy]
      resources :schedule_recurrences, only: %i[create]
      resources :schedule_occurrences, only: %i[create]
      resources :alarms, only: %i[index new create edit update destroy]
    end
  end

  resources :main, only: %i[index]
  resources :users, only: %i[index update], param: :username

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .d-flex.justify-content-between.align-items-center
      .copyright
        = t(:copyright)
      .text-muted.text-align-end
        = t(:timezone_notice_html, timezone: local_time(Time.zone.now, format: '%Z'))
      %ul.list-inline.mb-0
        %li.list-inline-item
          = link_to t(:source_code), 'https://github.com/openSUSE/calendar-o-o'
        %li.list-inline-item
          = link_to t(:license),
                    'https://github.com/openSUSE/calendar-o-o/blob/main/LICENSE'

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-sm
  .container-fluid
    = render 'theme/brand'
    %button.navbar-toggler{ data: { bs: { target: '#navbar-content',
                                          toggle: 'collapse' } },
                            type: 'button',
                            aria: { controls: 'navbar-content',
                                    expanded: 'false',
                                    label: t(:toggle_nav) } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-content
      %ul.navbar-nav.me-auto
        %li.nav-item
          = link_to t(:teams_nav), teams_path, class: 'nav-link'
        %li.nav-item
          = render partial: 'shared/subscribe_links', locals: { url: main_index_url(format: :ics),
                                                                button_class: 'nav-link' }
      .navbar-nav
        - if user_signed_in?
          .dropdown.nav-item
            %a.nav-link.dropdown-toggle{ 'aria-expanded': 'false', href: '#',
                                         role: 'button',
                                         'data-bs-toggle': 'dropdown' }
              = avatar current_user
              = current_user.name
            %ul.dropdown-menu.dropdown-menu-end
              %li
                = link_to t(:my_teams), teams_path(user: current_user.username), class: 'dropdown-item'
              - if policy(User).index?
                %li
                  = link_to t(:manage_users), users_path, class: 'dropdown-item'
              %li
                %hr.dropdown-divider
              %li
                = button_to t(:log_out), destroy_user_session_path,
                            method: :delete,
                            class: 'dropdown-item text-danger'
        - else
          %button.btn.btn-primary{ type: 'button', data: { 'bs-toggle': 'modal',
                                                           'bs-target': '#sign-in-modal' } } Sign in
          = render partial: 'layouts/sign_in_modal'

app/views/layouts/_sign_in_modal.html.haml
.modal.fade#sign-in-modal{ tabindex: -1 }
  .modal-dialog
    .modal-content
      .modal-header
        %h5.mb-0= t(:sign_in)
        %button.btn-close{ type: 'button', data: { 'bs-dismiss': 'modal' }, aria: { label: t(:close) } }
      .modal-body
        - if Devise.mappings[:user].registerable?
          = link_to t(:sign_up), new_registration_path(:user),
                    class: 'btn btn-light d-block mb-1'
        - Rails.configuration.site.dig(:authentication, :sign_up)&.each do |sign_up|
          = link_to t(:sign_up_to, provider: sign_up[:name]), sign_up[:link], class: 'btn btn-light d-block mb-1'
      .text-center
        = t(:or)
      - if Devise.mappings[:user].omniauthable?
        .modal-body
          - providers = Rails.configuration.site.dig(:authentication, :omniauth)&.to_h { |_k, v| [v[:name], v[:title]] }
          - User.omniauth_providers.each do |provider|
            = button_to t(:sign_in_with, provider: providers[provider]), omniauth_authorize_path(:user, provider),
                        data: { turbo: false }, class: 'btn btn-light w-100 mb-1'
      - if Devise.mappings[:user].database_authenticatable?
        = form_for(User.new, as: :user, url: session_path(:user)) do |f|
          .modal-body
            .form-floating.mb-3
              = f.text_field :username, autofocus: true, autocomplete: 'username',
                                        placeholder: t(:username), class: 'form-control'
              = f.label :username, t(:username)
            .form-floating.mb-3
              = f.password_field :password, autocomplete: 'current-password',
                                            placeholder: t(:password), class: 'form-control'
              = f.label :password, t(:password)
            - if Devise.mappings[:user].rememberable?
              .form-check.mb-3
                = f.check_box :remember_me, class: 'form-check-input'
                = f.label :remember_me, t(:remember_me), class: 'form-check-label'
            = render 'shared/devise_links'
          .modal-footer
            %button.btn.btn-secondary{ type: 'button', data: { 'bs-dismiss': 'modal' } }= t(:close)
            = f.submit t(:log_in), class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title= Rails.configuration.site[:program_name]
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags 'application'
    = favicon_link_tag 'favicon.ico'
    = yield :head
  %body
    = render partial: 'layouts/navbar'
    .toast-container.position-fixed.bottom-0.end-0.p-3
      - flash.each do |type, text|
        - type = 'success' if type == 'notice'
        - type = 'danger' if type == 'alert'
        %div{ class: "toast align-items-center text-bg-#{type} border-0 show",
              aria: { atomic: 'true', live: 'assertive' }, role: 'alert' }
          .d-flex
            .toast-body
              = text
            %button.btn-close.me-2.m-auto{ 'aria-label': t(:close),
                                           'data-bs-dismiss': 'toast',
                                           type: 'button' }
    %main.flex-fill.d-flex.h-100
      .container.my-3.flex-fill
        = yield
    = render partial: 'layouts/footer'